name: Main
on:
  pull_request:

jobs:
  scout:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: Scout SBOM
        uses: eunomie/scout-action@main
        with:
          command: sbom
          debug: true
          image: golang:1.20.2-alpine

      - name: Scout SBOM
        uses: eunomie/scout-action@main
        with:
          command: sbom
          debug: true
          image: golang:1.19.4-alpine3.16

      - name: Scout Quickview
        id: quickview
        uses: eunomie/scout-action@main
        with:
          command: quickview
          debug: true
          image: golang:1.20.2-alpine

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: ${{ steps.quickview.outputs.quickview }}
          token: ${{ secrets.GH_TOKEN }}

      - name: Scout compare
        id: compare
        uses: eunomie/scout-action@main
        with:
          command: compare
          debug: true
          image: golang:1.20.2-alpine
          to: golang:1.19.4-alpine3.16

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: ${{ steps.compare.outputs.compare }}
          token: ${{ secrets.GH_TOKEN }}
