name: Main
on:
  pull_request:

jobs:
  scout:
    permissions: write-all
    runs-on: ubuntu-latest
    env:
      DOCKER_SCOUT_CACHE_FORMAT: tar
      DOCKER_SCOUT_NO_CACHE: true
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Scout Quickview
        id: quickview
        uses: eunomie/scout-action@main
        with:
          command: quickview
          debug: true
          image: golang:1.20.2-alpine
          github-token: ${{ secrets.GITHUB_TOKEN }}
          write-comment: true
          hide-previous-comments: true

      - name: Scout compare
        id: compare
        uses: eunomie/scout-action@main
        with:
          command: compare
          debug: true
          image: golang:1.20.2-alpine
          to: golang:1.19.4-alpine3.16
          github-token: ${{ secrets.GITHUB_TOKEN }}
          write-comment: false
          hide-previous-comments: false
          
      - name: Scout compare
        id: node
        uses: eunomie/scout-action@main
        with:
          command: compare
          debug: true
          image: node:16-alpine
          to: node:18-alpine
          github-token: ${{ secrets.GITHUB_TOKEN }}
          write-comment: true
          hide-previous-comments: true
