name: Main
on:
  pull_request:

jobs:
  scout:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Scout Quickview
        id: quickview
        uses: eunomie/scout-action@main
        with:
          command: quickview
          debug: true
          image: golang:1.20.2-alpine
          github-token: ${{ secrets.GITHUB_TOKEN }}
          write-comment: true
          keep-previous-comments: true
