name: Main
on:
  pull_request:

jobs:
  scout:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2.5.0

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4.4.0
        with:
          images: eunomie/test-scout-action
          labels: org.opencontainers.image.revision=${{ env.SHA }}
          tags: latest

      - uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: false
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
        
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}

      - uses: eunomie/scout-action@main
        with:
          command: quickview,cves
          
      #- uses: eunomie/scout-action@main
      #  with:
      #    github-token: ${{ secrets.GITHUB_TOKEN }}
      #    command: quickview
      #    image: golang:1.20.2-alpine
          
      #- uses: eunomie/scout-action@main
      #  with:
      #    github-token: ${{ secrets.GITHUB_TOKEN }}
      #    command: quickview,compare
      #    image: golang:1.20.2-alpine
      #    to: golang:1.19.4-alpine3.16
      #    exit-code: false

      - uses: eunomie/scout-action@main
        with:
          command: cves
          image:  neo4j@sha256:ff8fdd8fa41b61631246e4e52de9f43a83a53b816d8c369212ba28a8c64f81e6

      - uses: eunomie/scout-action@main
        with:
          command: cves
          image: yvesbrissaud/learn:1.0.1
