name: Main
on:
  pull_request:

jobs:
  scout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2.5.0
      - name: Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Extract Docker metadata
        id: meta-with
        uses: docker/metadata-action@v4.4.0
        with:
          images: yvesbrissaud/demo-provenance
          labels: org.opencontainers.image.revision=${{ env.SHA }}
          tags: with

      - name: Docker Build
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          push: true
          load: false
          tags: ${{ steps.meta-with.outputs.tags }}
          labels: ${{ steps.meta-with.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            key:with

      - name: Extract Docker metadata
        id: meta-without
        uses: docker/metadata-action@v4.4.0
        with:
          images: yvesbrissaud/demo-provenance
          labels: org.opencontainers.image.revision=${{ env.SHA }}
          tags: without

      - name: Docker Build
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          push: true
          load: false
          tags: ${{ steps.meta-without.outputs.tags }}
          labels: ${{ steps.meta-without.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          sbom: false
          provenance: false
          build-args: |
            key:without

      - name: Extract Docker metadata
        id: meta-with-min
        uses: docker/metadata-action@v4.4.0
        with:
          images: yvesbrissaud/demo-provenance
          labels: org.opencontainers.image.revision=${{ env.SHA }}
          tags: with-min

      - name: Docker Build
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          push: true
          load: false
          tags: ${{ steps.meta-with-min.outputs.tags }}
          labels: ${{ steps.meta-with-min.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          sbom: true
          provenance: mode=min
          build-args: |
            key:with-min
